version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.11-stretch

    working_directory: /go/src/github.com/giantswarm/gsclientgen

    steps:
      - checkout

      - run:
          name: Install dep
          command: |
            go get -u github.com/golang/dep/cmd/dep
            dep version

      - run: make build
