// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V4ClusterDetailsResponseWorkersItemsCPU v4 cluster details response workers items Cpu
// swagger:model v4ClusterDetailsResponseWorkersItemsCpu
type V4ClusterDetailsResponseWorkersItemsCPU struct {

	// Number of CPU cores
	// Minimum: 2
	Cores int64 `json:"cores,omitempty"`
}

// Validate validates this v4 cluster details response workers items Cpu
func (m *V4ClusterDetailsResponseWorkersItemsCPU) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCores(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V4ClusterDetailsResponseWorkersItemsCPU) validateCores(formats strfmt.Registry) error {

	if swag.IsZero(m.Cores) { // not required
		return nil
	}

	if err := validate.MinimumInt("cores", "body", int64(m.Cores), 2, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V4ClusterDetailsResponseWorkersItemsCPU) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V4ClusterDetailsResponseWorkersItemsCPU) UnmarshalBinary(b []byte) error {
	var res V4ClusterDetailsResponseWorkersItemsCPU
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
