// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V5AddNodePoolRequestScaling Attributes specific to cluster node scaling. To have full control of
// the cluster size, min and max can be set to the same value, however `max`
// must be greater or equal to `min`. If only `min` or only `max` is specified,
// `min` and `max` will be set equally.
//
// swagger:model v5AddNodePoolRequestScaling
type V5AddNodePoolRequestScaling struct {

	// Maximum number of nodes in the pool.
	// Minimum: 0
	Max *int64 `json:"max,omitempty"`

	// Minimum number of nodes in the pool.
	// Minimum: 0
	Min *int64 `json:"min,omitempty"`
}

// Validate validates this v5 add node pool request scaling
func (m *V5AddNodePoolRequestScaling) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMax(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMin(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V5AddNodePoolRequestScaling) validateMax(formats strfmt.Registry) error {

	if swag.IsZero(m.Max) { // not required
		return nil
	}

	if err := validate.MinimumInt("max", "body", int64(*m.Max), 0, false); err != nil {
		return err
	}

	return nil
}

func (m *V5AddNodePoolRequestScaling) validateMin(formats strfmt.Registry) error {

	if swag.IsZero(m.Min) { // not required
		return nil
	}

	if err := validate.MinimumInt("min", "body", int64(*m.Min), 0, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V5AddNodePoolRequestScaling) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V5AddNodePoolRequestScaling) UnmarshalBinary(b []byte) error {
	var res V5AddNodePoolRequestScaling
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
