// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V5AddNodePoolRequestNodeSpecAwsInstanceDistribution Attributes defining the instance distribution in a node pool.
//
// swagger:model v5AddNodePoolRequestNodeSpecAwsInstanceDistribution
type V5AddNodePoolRequestNodeSpecAwsInstanceDistribution struct {

	// Base capacity of on demand machines.
	//
	OnDemandBaseCapacity int64 `json:"on_demand_base_capacity,omitempty"`

	// Percentage of on demand instances above the base capacity.
	//
	OnDemandPercentageAboveBaseCapacity int64 `json:"on_demand_percentage_above_base_capacity,omitempty"`
}

// Validate validates this v5 add node pool request node spec aws instance distribution
func (m *V5AddNodePoolRequestNodeSpecAwsInstanceDistribution) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V5AddNodePoolRequestNodeSpecAwsInstanceDistribution) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V5AddNodePoolRequestNodeSpecAwsInstanceDistribution) UnmarshalBinary(b []byte) error {
	var res V5AddNodePoolRequestNodeSpecAwsInstanceDistribution
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
